apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mitmproxy
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mitmproxy
      containers:
      - args:
        - mitmweb
        - --web-host
        - "*"
        - --no-web-open-browser
        image: mitmproxy/mitmproxy:dev
        imagePullPolicy: Always
        livenessProbe:
         failureThreshold: 3
         initialDelaySeconds: 125
         periodSeconds: 180
         successThreshold: 1
         tcpSocket:
          port: 8081
         timeoutSeconds: 1
        readinessProbe:
         failureThreshold: 3
         initialDelaySeconds: 5
         periodSeconds: 120
         successThreshold: 1
         tcpSocket:
          port: 8081
         timeoutSeconds: 1
        name: mitmproxy
        stdin: true
        tty: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      hostNetwork: true
      imagePullSecrets:
        - name: registry-1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30